name: Maven Build Artifact

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  build:
    uses: valitydev/java-workflow/.github/workflows/maven-service-build.yml@v3
